add commentbox functionality, including: validation, vuex for storing…
kterekh/Vue.app pull request #12
Opened 2021-02-09 17:11 UTC by kterekh

… comments and deleting

2021-02-09 17:42 UTC, silchencko requested changes
Looks good to me! good work with vuex!

2021-02-09 17:42 UTC, silchencko commented on src/common/Button.vue
> +  @Prop({ required: false }) iconClass!: string
iconClass is not required. What if there is no iconClass? What will happen to `<i>`?

2021-02-09 17:42 UTC, silchencko commented on src/common/Comment.vue
> +    return this.$store.state.b.comments
Please find more meaningful name for the `b` module

2021-02-09 17:42 UTC, silchencko commented on src/common/Comment.vue
> +  @Prop({ required: false }) iconClass!: string
if iconClass is not required, what will happen to template?

2021-02-09 17:42 UTC, silchencko commented on src/common/TextArea.vue
> +  @Prop() comment!: string
Maybe `label` instead of `comment`?

2021-02-09 17:42 UTC, silchencko commented on src/common/Button.vue
> +    <i class="far" :class="iconClass"></i>
My suggestion: hide this element if `iconClass` is not defined

2021-02-09 17:42 UTC, silchencko commented on src/components/FormDemoComponent.vue
> +      comment="Comment:"
`label`?

2021-02-09 17:42 UTC, silchencko commented on src/common/Comment.vue
> +export default class Comment extends Vue {
My suggestion is to call this class `Comments`  if it has multiple comments

2021-02-10 08:10 UTC, kterekh commented on src/common/Button.vue
> +  @Prop({ required: false }) iconClass!: string
Hmm, still will be rendered. How to avoid this?

2021-02-10 08:16 UTC, kterekh commented on src/common/Button.vue
> +    <i class="far" :class="iconClass"></i>
Got it, v-if will help here.

2021-02-10 09:21 UTC, silchencko approved these changes

2021-02-10 09:21 UTC, merged