Alert component with added link is created
kterekh/Vue.app pull request #2
Opened 2021-01-22 12:10 UTC by kterekh

Alert component is created: https://trello.com/c/i6rgDHzF/9-create-alert-component

@silchencko please review.

2021-01-22 12:44 UTC, silchencko reviewed
@kterekh Looks great! Good job! And good progress with the second component!
I left some comments to make it even better.
Please don't hesitate to use `npm run lint --fix` before commit

2021-01-22 12:44 UTC, silchencko commented on src/App.vue
> +    <app-button title="button" v-bind:color="btnColor.Primary" size="lg" v-bind:is-disabled="true"
```suggestion
    <app-button
      title="button"
      v-bind:color="btnColor.Primary"
      size="lg" v-bind:is-disabled="true"
      v-bind:action=" () => showAlert('Hello!')" />
```
My suggestion is to align attributes. If you have nothing between `<app-button...>` and `</app-button>`, you can shorten it: `<app-button... />`

2021-01-22 12:44 UTC, silchencko commented on src/common/Alert.vue
> +<style lang="scss">
remove `<style lang="scss">.  </style>` if you don't use it

2021-01-22 12:44 UTC, silchencko commented on src/common/Alert.vue
> +      <a v-bind:href="linkValue">{{linkTitle}}</a>
I'd add `v-if="linkValue"` to render it only when `linkValue` and `linkTitle` are defined

2021-01-22 12:44 UTC, silchencko commented on src/App.vue
> +  link: true,
Do you use `link: true ` ?

2021-01-22 12:44 UTC, silchencko commented on src/common/Alert.vue
> +    linkValue: {
Maybe it makes sense to keep link value and link title in one object:
```
link: {
  title: 'link',
  value: 'http://link.com'
}
```
If you use it, you will need an interface with title and value properties
This is up to you

2021-01-22 12:44 UTC, silchencko commented on src/common/Alert.vue
> +      type: String,
hm, do you use `role` somewhere in Alert component?

2021-01-22 13:14 UTC, kterekh commented on src/common/Alert.vue
> +      type: String,
No, thanks for paying attention to details.  It was as part of my first idea to implement this alert. Deleted it.

2021-01-22 13:19 UTC, kterekh commented on src/App.vue
> +    <app-button title="button" v-bind:color="btnColor.Primary" size="lg" v-bind:is-disabled="true"
Make sense, thanks!

2021-01-22 13:26 UTC, kterekh commented on src/common/Alert.vue
> +    linkValue: {
Let's discuss it on our call today.

2021-01-22 13:26 UTC, kterekh commented on src/App.vue
> +  link: true,
Let's discuss it on our call today.

2021-01-22 14:57 UTC, kterekh commented on src/common/Alert.vue
> +      <a v-bind:href="linkValue">{{linkTitle}}</a>
Done.

2021-01-25 12:54 UTC, silchencko requested changes

2021-01-25 12:54 UTC, silchencko commented on src/common/Button.vue
> +  @Prop() isDisabled!: string
isDisabled - boolean

2021-01-25 13:01 UTC, silchencko commented on src/common/Button.vue
> +  name = 'Button'
You don't need name

2021-01-25 13:15 UTC, silchencko approved these changes

2021-01-25 13:15 UTC, merged

2021-01-25 14:08 UTC, silchencko commented on src/App.vue
> +  linkAvailable = true
: boolean

2021-01-25 14:08 UTC, silchencko commented on src/common/Alert.vue
> +  @Prop() color!: string
@Prop({ required: true })
color!: alertColor